### ISSUE TITLE
Examples on How to Use

### ISSUE THREAD

**Issue by lylepratt** [seanbright/mod_amd#4]
Howdy,

Would you mind posting some example code on how to use this module? I see configuration instructions in the README, but no information on how to actually use it. Even a cut/paste from a past project would be good. Once @thomasquintana and I have a good understanding of it, I will post a Pull Request with an update to the README if needed.

**Comment by seanbright** [comment]
As I mentioned in the other issue, I haven't run FS for nearly 2 years, so I don't remember. Glancing at the code it looks like there are two variables that get set: {{amd_result}} and {{amd_cause}} indiciating if a machine or human or otherwise was detected. So you would just need the "dialplan" (or whatever it is called in FS) to invoke the amd app on an outbound call and then when it returns it will have set those 2 variables.

**Comment by lylepratt** [comment]
OK. I understand that you have not used it in a while, but I was hoping you had some old code around where you had used it in the past. Currently the module does not seem to supply an `amd` command at all that you could even "invoke". We will continue playing with it.

**Comment by seanbright** [comment]
I do not have old code around. Looking at the code is creates an "app" called "amd." Is there a command to get a list of registered apps? Based on my best guess, you would need something like this:

    <action application="amd"/>

**Comment by lylepratt** [comment]
Just reporting back that we have this working and its working rather well so far!
